general {
    hide_cursor = true
}

background {
    monitor =
    color = rgb(282828)
}

label {
    monitor =
    text = $TIME
    color = rgb(ebdbb2)
    font_size = 48
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    position = 0, -20
    halign = center
    valign = center
    outer_color = rgb(fe8019)
    inner_color = rgb(3c3836)
    font_color = rgb(ebdbb2)
    placeholder_text = <i>password</i>
}
