vim.g.mapleader = " "

local o = vim.opt
o.number = true
o.relativenumber = true
o.tabstop = 4
o.shiftwidth = 4
o.expandtab = true
o.ignorecase = true
o.smartcase = true
o.termguicolors = true
o.signcolumn = "yes"
o.clipboard = "unnamedplus"
o.undofile = true
o.scrolloff = 8
o.splitright = true
o.splitbelow = true
o.completeopt = { "menu", "menuone", "noselect" }
o.timeoutlen = 400

-- lazy.nvim bootstrap
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(lazypath)

local langs = { "lua", "go", "gomod", "bash", "dart", "markdown", "json", "yaml" }

require("lazy").setup({
  { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
  { "ellisonleao/gruvbox.nvim", priority = 1000 },
  { "shaunsingh/nord.nvim", priority = 1000 },
  { "folke/tokyonight.nvim", priority = 1000 },
  { "rose-pine/neovim", name = "rose-pine", priority = 1000 },
  { "nvim-telescope/telescope.nvim", dependencies = { "nvim-lua/plenary.nvim" } },
  { "nvim-treesitter/nvim-treesitter", branch = "main", lazy = false, build = ":TSUpdate",
    config = function()
      require("nvim-treesitter").install(langs)
      vim.api.nvim_create_autocmd("FileType", {
        pattern = langs,
        callback = function() vim.treesitter.start() end,
      })
    end },
  { "neovim/nvim-lspconfig" },
  -- Org mode. Files stay .org in ~/orgfiles (synced by Syncthing). The
  -- org-bullets fork under nvim-orgmode is the maintained one; akinsho's
  -- errors on every org buffer against current nvim-orgmode.
  { "nvim-orgmode/orgmode", ft = { "org" }, lazy = false,
    dependencies = { "nvim-orgmode/org-bullets.nvim" },
    config = function()
      require("orgmode").setup({
        org_agenda_files = { "~/orgfiles/*.org", "~/orgfiles/zettelkasten/*.org" },
        org_default_notes_file = "~/orgfiles/refile.org",
        org_todo_keywords = { "TODO", "NEXT", "WAITING", "|", "DONE", "CANCELLED" },
        org_startup_folded = "content",

        -- Capture and the agenda open as a centred float rather than a
        -- 16-line split along the bottom of the screen. Journalling is what
        -- this is mostly used for, and a strip at the foot of a 3440px-wide
        -- monitor is a cramped and oddly-shaped place to write prose.
        win_split_mode = { "float", 0.85 },
        win_border = "rounded",

        -- Stars and emphasis markers are markup, not content. org-bullets
        -- already draws a bullet per level, so showing the stars as well is
        -- noise; hiding the leading ones leaves the bullet sitting at the
        -- indent its level implies. Needs conceallevel, which the plugin does
        -- not set itself — see the FileType autocmd near the bottom.
        org_hide_leading_stars = true,
        org_hide_emphasis_markers = true,
        org_ellipsis = "  ⋯",
        -- The existing journal body text sits flush left, not indented under
        -- the headline; keep new entries matching.
        org_adapt_indentation = false,
        org_capture_templates = {
          -- journal.org format: "* 2026-07-15 Wednesday", "** Title", body.
          -- A single-level datetree keeps that flat shape (the built-in "day"
          -- tree nests year/month/day) and reuses the same-day heading when a
          -- second entry is written on the same day instead of stacking dates.
          j = {
            description = "Journal",
            target = "~/orgfiles/journal.org",
            datetree = {
              tree_type = "custom",
              tree = { {
                format = "%Y-%m-%d %A",
                pattern = "^(%d%d%d%d)%-(%d%d)%-(%d%d).*$",
                order = { 1, 2, 3 },
              } },
            },
            template = "* %?",
          },
          t = {
            description = "Task",
            target = "~/orgfiles/todo.org",
            template = "* TODO %?\n  %U",
          },
        },
      })
      require("org-bullets").setup()
    end },
  { "folke/which-key.nvim", event = "VeryLazy",
    opts = {
      spec = {
        { "<leader>f", group = "find" },
        { "<leader>c", group = "code" },
        { "<leader>r", group = "refactor" },
        { "<leader>o", group = "org" },
        { "<leader>of", group = "org files" },
      },
    } },
})

-- theme.lua is generated by theme/apply.sh and now carries the whole palette,
-- not just a name. Tolerant of the old single-string form so a stale file
-- leaves you with a working editor rather than a broken one.
local theme = require("theme")
local palette = type(theme) == "table" and theme or { colorscheme = theme }
vim.cmd.colorscheme(palette.colorscheme)

-- Org headline colours, one per level, from that palette.
--
-- nvim-orgmode links these to Title/Constant/Identifier/Statement/PreProc/
-- Type/Special/String, which borrows whatever the colorscheme chose for code.
-- The result is arbitrary as a hierarchy — in gruvbox levels 2 and 5 come out
-- nearly the same — and it has nothing to do with the palette the rest of the
-- desktop is built from. This is a deliberate cascade instead, warm at the top
-- and cooling as you nest, bold for the three levels you actually navigate by.
--
-- Scheduled rather than called directly: nvim-orgmode re-applies its own links
-- on every ColorScheme event, so this has to run after them. vim.schedule puts
-- it after all synchronous handlers instead of relying on the order autocmds
-- happen to have been registered in.
local org_levels = {
  palette.accent, palette.yellow, palette.green, palette.blue,
  palette.magenta, palette.cyan, palette.red, palette.dim,
}
local function org_headline_colours()
  for i, colour in ipairs(org_levels) do
    if colour then
      vim.api.nvim_set_hl(0, "@org.headline.level" .. i, { fg = colour, bold = i <= 3 })
    end
  end
end
vim.api.nvim_create_autocmd("ColorScheme", {
  pattern = "*",
  callback = function() vim.schedule(org_headline_colours) end,
})
vim.schedule(org_headline_colours)

-- LSP
vim.lsp.enable({ "gopls", "lua_ls", "clangd" })

vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(ev)
    local client = vim.lsp.get_client_by_id(ev.data.client_id)
    if client and client:supports_method("textDocument/completion") then
      vim.lsp.completion.enable(true, client.id, ev.buf, { autotrigger = true })
    end
    local map = function(keys, fn, desc)
      vim.keymap.set("n", keys, fn, { buffer = ev.buf, desc = desc })
    end
    map("gd", vim.lsp.buf.definition, "Go to definition")
    map("gr", vim.lsp.buf.references, "References")
    map("K", vim.lsp.buf.hover, "Hover docs")
    map("<leader>rn", vim.lsp.buf.rename, "Rename symbol")
    map("<leader>ca", vim.lsp.buf.code_action, "Code action")
    map("<leader>cd", vim.diagnostic.open_float, "Line diagnostics")
  end,
})

-- format Go on save
vim.api.nvim_create_autocmd("BufWritePre", {
  pattern = { "*.go", "*.c", "*.h" },
  callback = function() vim.lsp.buf.format({ async = false }) end,
})

-- keymaps
local map = function(keys, fn, desc)
  vim.keymap.set("n", keys, fn, { desc = desc })
end
map("<leader>ff", "<cmd>Telescope find_files<cr>", "Files")
map("<leader>fg", "<cmd>Telescope live_grep<cr>", "Grep")
map("<leader>fb", "<cmd>Telescope buffers<cr>", "Buffers")
map("<leader>fr", "<cmd>Telescope oldfiles<cr>", "Recent files")
map("<leader>fh", "<cmd>Telescope help_tags<cr>", "Help")
map("<leader>fm", "<cmd>Telescope man_pages<cr>", "Man pages")
map("<leader>w", "<cmd>w<cr>", "Save")
map("<leader>q", "<cmd>q<cr>", "Quit")
map("<leader>e", "<cmd>Explore<cr>", "File explorer")
map("<leader>?", "<cmd>WhichKey<cr>", "All keymaps")

-- org: capture is <leader>oc and agenda <leader>oa (nvim-orgmode defaults).
-- <leader>ocj goes straight to a journal entry without the template menu.
map("<leader>ofj", "<cmd>edit ~/orgfiles/journal.org<cr>", "Journal")
map("<leader>oft", "<cmd>edit ~/orgfiles/todo.org<cr>", "Todo")
map("<leader>ofs", "<cmd>edit ~/orgfiles/shell-in-c-12-weeks.org<cr>", "Shell in C plan")
map("<leader>ofr", "<cmd>edit ~/orgfiles/refile.org<cr>", "Refile")
map("<leader>ocj", function() require("orgmode").capture:open_template_by_shortcut("j") end, "Journal entry")
map("<Esc>", "<cmd>nohlsearch<cr>", "Clear search")

-- Org buffers are prose, so they get prose settings rather than the code
-- defaults. conceallevel is the load-bearing one: org_hide_leading_stars and
-- org_hide_emphasis_markers are both implemented with conceal, and nvim-orgmode
-- does not set it, so without this they are configured and do nothing.
--
-- concealcursor is deliberately left empty: markers reappear on the line the
-- cursor is on, which is what you want while editing and not while reading.
vim.api.nvim_create_autocmd("FileType", {
  pattern = "org",
  callback = function()
    vim.opt_local.conceallevel = 2
    vim.opt_local.concealcursor = ""
    vim.opt_local.wrap = true
    vim.opt_local.linebreak = true    -- break between words, not mid-word
    vim.opt_local.breakindent = true  -- continuation lines keep the indent
    vim.opt_local.number = false      -- line numbers earn nothing in prose
    vim.opt_local.relativenumber = false

    -- Spell check. en_au rather than plain en, so "color" is flagged and
    -- "colour" is not; both are in the one en.utf-8.spl that ships with nvim,
    -- so this needs nothing downloaded.
    --
    -- Not as noisy as it sounds: nvim-orgmode's treesitter highlights.scm
    -- marks headlines, paragraphs and list items @spell, and TODO/DONE
    -- keywords and link URLs @nospell, so only prose is checked. Property
    -- drawers, timestamps and #+DIRECTIVES are never captured and so are
    -- skipped too.
    vim.opt_local.spell = true
    vim.opt_local.spelllang = "en_au"

    -- The personal dictionary lives with the journal, not in this repo. zg on
    -- a name writes it here, Syncthing carries it to the other machine, and it
    -- stays out of a public repo — the words you add are mostly the names of
    -- people and places you know.
    local dict = vim.fn.expand("~/orgfiles/spell")
    if vim.fn.isdirectory(dict) == 0 then
      vim.fn.mkdir(dict, "p")
    end
    vim.opt_local.spellfile = dict .. "/en.utf-8.add"

    -- See the checktime autocmds below for why this matters here.
    vim.opt_local.autoread = true
  end,
})

-- Syncthing carries ~/orgfiles between the two machines, and it does not merge.
-- When the same file changes in both places it keeps one copy and parks the
-- other as journal.sync-conflict-<date>.org, which is easy not to notice — one
-- sat here for two days holding an entry that existed nowhere else.
--
-- The usual way to cause that is to leave the journal open in nvim on one
-- machine and write on the other: the buffer here is now stale, and the next
-- :w sends a whole file back that never saw the other machine's entry.
--
-- autoread fixes the harmless half of that — an unmodified buffer quietly
-- takes the newer file — but autoread only acts when nvim looks, and nvim only
-- looks on certain events. checktime is what makes it look. The dangerous half
-- (changed on disk AND unsaved changes here) nvim refuses to resolve on its
-- own and prompts, which is the correct answer: that one needs a human.
--
-- Registered once at top level, not inside the FileType callback, which would
-- add another copy of each autocmd for every org buffer opened.
vim.api.nvim_create_autocmd({ "FocusGained", "BufEnter", "CursorHold" }, {
  pattern = "*.org",
  command = "silent! checktime",
})

vim.api.nvim_create_autocmd("FileChangedShellPost", {
  pattern = "*.org",
  callback = function(ev)
    vim.notify(
      ("%s changed on disk and was reloaded"):format(vim.fn.fnamemodify(ev.file, ":t")),
      vim.log.levels.WARN
    )
  end,
})

-- jk leaves insert mode, the habit carried over from evil-escape in Doom.
-- Also mapped in terminal mode, where <Esc> is usually swallowed by the shell.
-- timeoutlen is 400 above, which is what keeps the pause after a lone "j"
-- short enough not to notice.
vim.keymap.set("i", "jk", "<Esc>", { desc = "Exit insert mode" })
vim.keymap.set("t", "jk", [[<C-\><C-n>]], { desc = "Exit terminal mode" })
