music_directory     "~/Music"
playlist_directory  "~/.local/state/mpd/playlists"
db_file             "~/.local/state/mpd/database"
state_file          "~/.local/state/mpd/state"
sticker_file        "~/.local/state/mpd/sticker.sql"
bind_to_address     "localhost"
auto_update         "yes"
restore_paused      "yes"

audio_output {
    type    "pipewire"
    name    "PipeWire"
}
