#!/usr/bin/env bash
# Detects CPU and GPU and installs what this machine needs. Runs on every
# machine, with or without a hosts/<name>/ folder, so a brand new box needs
# no manual step. Writes dotfiles/hypr/hardware.conf, sourced by hyprland.conf.
#
# Safe and cheap to re-run: every file is written only when its content would
# actually change, and the initramfs is rebuilt only when a drop-in changed.
set -euo pipefail
DOTS="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONF="$DOTS/dotfiles/hypr/hardware.conf"
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/dots"
PKGS=()

# Built in memory, written once at the end. No date stamp: the output must be a
# function of the hardware alone, or every run looks like a change.
CONF_TEXT="# Generated by scripts/hardware.sh. Do not edit.
# Re-run install.sh to regenerate."

# Hyprland errors on a missing source, so guarantee the file exists before any
# step that could fail. The real content lands further down.
[ -f "$CONF" ] || printf '%s\n' "$CONF_TEXT" > "$CONF"

# Replace a root-owned drop-in only when its content differs. Returns 0 when it
# wrote, 1 when the file was already correct; callers use that to decide whether
# the initramfs needs rebuilding. The drop-ins are 644, so the compare needs no
# sudo — only the write does.
write_dropin() {
    local path="$1" content="$2"
    if [ -f "$path" ] && [ "$(cat "$path")" = "$content" ]; then
        return 1
    fi
    sudo mkdir -p "$(dirname "$path")"
    printf '%s\n' "$content" | sudo tee "$path" >/dev/null
}

# ---- CPU microcode -------------------------------------------------------
# The repo ships no microcode; without this a fresh machine gets none.
case "$(awk -F': ' '/^vendor_id/{print $2; exit}' /proc/cpuinfo)" in
    AuthenticAMD) UCODE=amd-ucode ;;
    GenuineIntel) UCODE=intel-ucode ;;
    *)            UCODE="" ;;
esac
[ -n "$UCODE" ] && PKGS+=("$UCODE")

# ---- GPU -----------------------------------------------------------------
# Vendor IDs from the VGA/3D controller class, not lspci's human-readable text.
GPUS=$(lspci -nn -d ::0300; lspci -nn -d ::0302) || true

if grep -q '\[10de:' <<<"$GPUS"; then
    echo "==> NVIDIA detected"
    # DKMS needs headers for whichever kernel is installed.
    KERNEL=$(pacman -Qqs '^linux(-zen|-lts|-hardened)?$' | head -1 || true)
    [ -n "$KERNEL" ] && PKGS+=("$KERNEL-headers")
    PKGS+=(nvidia-open-dkms nvidia-utils libva-nvidia-driver egl-wayland)
    # lib32-nvidia-utils needs multilib; skip rather than fail the whole run.
    if grep -q '^\[multilib\]' /etc/pacman.conf; then
        PKGS+=(lib32-nvidia-utils)
    else
        echo "    multilib not enabled — skipping lib32-nvidia-utils"
    fi

    CONF_TEXT+="

# NVIDIA. Values match the recipe verified working on the RTX 3060.
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# XWayland renders blurry on NVIDIA without this.
xwayland {
    force_zero_scaling = true
}"

    # Early KMS via drop-ins, so the main mkinitcpio.conf is never rewritten.
    # Only a genuine content change costs an initramfs rebuild.
    if write_dropin /etc/modprobe.d/nvidia.conf \
        'options nvidia_drm modeset=1'; then
        echo "    wrote /etc/modprobe.d/nvidia.conf"
        NEED_INITRD=1
    fi
    if write_dropin /etc/mkinitcpio.conf.d/nvidia.conf \
        'MODULES+=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)'; then
        echo "    wrote /etc/mkinitcpio.conf.d/nvidia.conf"
        NEED_INITRD=1
    fi

elif grep -q '\[8086:' <<<"$GPUS"; then
    echo "==> Intel graphics detected"
    PKGS+=(intel-media-driver)
    CONF_TEXT+="

env = LIBVA_DRIVER_NAME,iHD"

elif grep -q '\[1002:' <<<"$GPUS"; then
    echo "==> AMD graphics detected"
    PKGS+=(libva-mesa-driver mesa-vdpau)
    CONF_TEXT+="

env = LIBVA_DRIVER_NAME,radeonsi"
else
    echo "==> No discrete GPU matched; using defaults"
fi

# ---- btrfs rollback tooling ---------------------------------------------
# The README's recovery procedure is useless without these.
if [ "$(findmnt -n -o FSTYPE /)" = btrfs ]; then
    PKGS+=(btrfs-progs)
fi

# ---- hardware.conf -------------------------------------------------------
if [ "$(cat "$CONF")" != "$CONF_TEXT" ]; then
    printf '%s\n' "$CONF_TEXT" > "$CONF"
    echo "==> Hardware config written to dotfiles/hypr/hardware.conf"
else
    echo "==> Hardware config already current"
fi

# What this machine needs because of its hardware, recorded so `dots status`
# can tell hardware packages apart from packages installed by hand.
mkdir -p "$CACHE"
if [ ${#PKGS[@]} -gt 0 ]; then
    printf '%s\n' "${PKGS[@]}" > "$CACHE/hardware-pkgs"
else
    : > "$CACHE/hardware-pkgs"
fi

# ---- install -------------------------------------------------------------
if [ ${#PKGS[@]} -gt 0 ]; then
    echo "==> Hardware packages: ${PKGS[*]}"
    sudo pacman -S --needed --noconfirm "${PKGS[@]}"
fi

# Rebuild the initramfs only when a drop-in changed the modules it contains.
if [ -n "${NEED_INITRD:-}" ]; then
    echo "==> Regenerating initramfs"
    sudo mkinitcpio -P
fi

# Microcode reaches the CPU either through the mkinitcpio `microcode` hook
# (current practice, leaves no initrd line) or through an explicit boot entry.
# Warn only when neither is true.
if [ -n "$UCODE" ] && [ -d /boot/loader/entries ] \
   && ! grep -q microcode /etc/mkinitcpio.conf \
   && ! grep -rq "$UCODE.img" /boot/loader/entries 2>/dev/null; then
    cat <<WARN

    WARNING: $UCODE is installed but no systemd-boot entry references it.
    Add this line above the existing initrd line in /boot/loader/entries/*.conf:
        initrd  /$UCODE.img
WARN
fi
