#!/usr/bin/env bash
# Detects CPU and GPU and installs what this machine needs. Runs on every
# machine, with or without a hosts/<name>/ folder, so a brand new box needs
# no manual step. Writes dotfiles/hypr/hardware.conf, sourced by hyprland.conf.
set -euo pipefail
DOTS="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONF="$DOTS/dotfiles/hypr/hardware.conf"
PKGS=()

# Written first so the file always exists; Hyprland errors on a missing source.
{
    echo "# Generated by scripts/hardware.sh on $(date -I). Do not edit."
    echo "# Re-run install.sh to regenerate."
} > "$CONF"

# ---- CPU microcode -------------------------------------------------------
# The repo ships no microcode; without this a fresh machine gets none.
case "$(awk -F': ' '/^vendor_id/{print $2; exit}' /proc/cpuinfo)" in
    AuthenticAMD) UCODE=amd-ucode ;;
    GenuineIntel) UCODE=intel-ucode ;;
    *)            UCODE="" ;;
esac
[ -n "$UCODE" ] && PKGS+=("$UCODE")

# ---- GPU -----------------------------------------------------------------
# Vendor IDs from the VGA/3D controller class, not lspci's human-readable text.
GPUS=$(lspci -nn -d ::0300; lspci -nn -d ::0302) || true

if grep -q '\[10de:' <<<"$GPUS"; then
    echo "==> NVIDIA detected"
    # DKMS needs headers for whichever kernel is installed.
    KERNEL=$(pacman -Qqs '^linux(-zen|-lts|-hardened)?$' | head -1 || true)
    [ -n "$KERNEL" ] && PKGS+=("$KERNEL-headers")
    PKGS+=(nvidia-open-dkms nvidia-utils libva-nvidia-driver egl-wayland)
    # lib32-nvidia-utils needs multilib; skip rather than fail the whole run.
    if grep -q '^\[multilib\]' /etc/pacman.conf; then
        PKGS+=(lib32-nvidia-utils)
    else
        echo "    multilib not enabled — skipping lib32-nvidia-utils"
    fi

    cat >> "$CONF" <<'NV'

# NVIDIA. Values match the recipe verified working on the RTX 3060.
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# XWayland renders blurry on NVIDIA without this.
xwayland {
    force_zero_scaling = true
}
NV

    # Early KMS via drop-ins, so the main mkinitcpio.conf is never rewritten.
    sudo mkdir -p /etc/modprobe.d /etc/mkinitcpio.conf.d
    echo 'options nvidia_drm modeset=1' | \
        sudo tee /etc/modprobe.d/nvidia.conf >/dev/null
    echo 'MODULES+=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)' | \
        sudo tee /etc/mkinitcpio.conf.d/nvidia.conf >/dev/null
    NEED_INITRD=1

elif grep -q '\[8086:' <<<"$GPUS"; then
    echo "==> Intel graphics detected"
    PKGS+=(intel-media-driver)
    echo -e "\nenv = LIBVA_DRIVER_NAME,iHD" >> "$CONF"

elif grep -q '\[1002:' <<<"$GPUS"; then
    echo "==> AMD graphics detected"
    PKGS+=(libva-mesa-driver mesa-vdpau)
    echo -e "\nenv = LIBVA_DRIVER_NAME,radeonsi" >> "$CONF"
else
    echo "==> No discrete GPU matched; using defaults"
fi

# ---- btrfs rollback tooling ---------------------------------------------
# The README's recovery procedure is useless without these.
if [ "$(findmnt -n -o FSTYPE /)" = btrfs ]; then
    PKGS+=(btrfs-progs)
fi

# ---- install -------------------------------------------------------------
if [ ${#PKGS[@]} -gt 0 ]; then
    echo "==> Hardware packages: ${PKGS[*]}"
    sudo pacman -S --needed --noconfirm "${PKGS[@]}"
fi

# Rebuild the initramfs only when a drop-in changed the modules it contains.
if [ -n "${NEED_INITRD:-}" ]; then
    echo "==> Regenerating initramfs"
    sudo mkinitcpio -P
fi

# Microcode reaches the CPU either through the mkinitcpio `microcode` hook
# (current practice, leaves no initrd line) or through an explicit boot entry.
# Warn only when neither is true.
if [ -n "$UCODE" ] && [ -d /boot/loader/entries ] \
   && ! grep -q microcode /etc/mkinitcpio.conf \
   && ! grep -rq "$UCODE.img" /boot/loader/entries 2>/dev/null; then
    cat <<WARN

    WARNING: $UCODE is installed but no systemd-boot entry references it.
    Add this line above the existing initrd line in /boot/loader/entries/*.conf:
        initrd  /$UCODE.img
WARN
fi

echo "==> Hardware config written to dotfiles/hypr/hardware.conf"
