set -g status-style "bg=#181825,fg=#cdd6f4"
set -g status-left-length 30
set -g status-left "#[bg=#cba6f7,fg=#1e1e2e,bold]  #S #[bg=#181825,fg=#cba6f7]#[default] "
set -g status-right "#[fg=#89b4fa] #(cat /etc/hostname)  #[fg=#a6e3a1]󰥔 %H:%M #[fg=#f9e2af]󰃭 %a %d %b "
set -g window-status-format "#[fg=#6c7086] #I #W "
set -g window-status-current-format "#[bg=#313244,fg=#cba6f7,bold] #I #W #[default]"
set -g window-status-separator ""
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#cba6f7"
set -g message-style "bg=#313244,fg=#cdd6f4"
